receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  # Export to shared ElasticSearch APM service
  otlphttp/apm:
    compression: none
    endpoint: http://apm-server:8200
    tls:
      insecure: true

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/apm]
    metrics:
      receivers: [otlp]
      exporters: [otlphttp/apm]
